Prog3 FF + MVC Milestone1/OrderPlacement.Web/Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OrderPlacement.Web.Models
{
    public class Member
    {
        [Display(Name ="MemberID")]
        [Required]
        public int MemberId { get; set; }
        [Display(Name ="AddressID")]
        [Required]
        public int AddressId { get; set; }
        [Display(Name ="Prefix")]
        public string Prefix { get; set; }
        [Display(Name = "FirstName")]
        public string FistName { get; set; }
        [Display(Name = "LastName")]
        public string LastName { get; set; }
        [Display(Name = "Date")]
        public DateTime BirthDate { get; set; }
        [Display(Name = "Status")]
        public char Status { get; set; }
    }
}

Prog3 FF + MVC Milestone1/OrderPlacement.Web/Models/MembersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OrderPlacement.Web.Models
{
    public class MembersViewModel
    {
        public Member EditedMember { get; set; }
        public List<Member> ListofMembers { get; set; }
    }
}

Prog3 FF + MVC Milestone1/OrderPlacement.Web/Controllers/MembersController.cs
using AutoMapper;
using OrderPlacement.Logic;
using OrderPlacement.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OrderPlacement.Data;
using System.Web.Mvc;
using OrderPlacement.Repository;

namespace OrderPlacement.Web.Controllers
{
    public class MembersController : Controller
    {
        MembersLogic logic;
        IMapper mapper;
        MembersViewModel vm;

        public MembersController()
        {
            OrderPlacementTablesEntities dbEntity = new OrderPlacementTablesEntities();
            MembersRepository repo = new MembersRepository();
            this.logic = new MembersLogic();
            this.mapper = MapperFactory.CreateMapper();
            vm = new MembersViewModel();
            vm.EditedMember = new Member();
            var members = logic.GetAllMembers();
            vm.ListofMembers = mapper.Map<IList<OrderPlacement.Data.Members>, List<Models.Member>>(members);
        }

        private Member GetMemberModel(int id)
        {
            Members oneCar = logic.GetOne(id);
            return mapper.Map<OrderPlacement.Data.Members, Models.Member>(oneCar);
        }

        // GET: Members
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("MemberIndex", vm);
        }

        // GET: Members/Details/5
        public ActionResult Details(int id)
        {
            return View("MemberDetails", GetMemberModel(id));
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedMember = GetMemberModel(id);
            return View("MemberIndex", vm);
        }

        // POST: Members/Edit/5
        [HttpPost]
        public ActionResult Edit(Member member, string editAction)
        {
            if (ModelState.IsValid && member != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.Add(member.MemberId, member.Prefix, member.FistName, member.LastName);
                }
                else
                {
                    bool success = logic.ChangeMember(member.MemberId, member.Prefix, member.FistName, member.LastName);
                    if (!success)
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedMember = member;
                return View("MemberIndex", vm);
            }
        }

        // GET: Members/Delete/5
        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete Fail";
            if (logic.Remove(id))
            {
                TempData["editResult"] = "Delete OK";
            }
            return RedirectToAction("Index");
        }
        
    }
}

Prog3 FF + MVC Milestone1/OrderPlacement.Web/Views/Members/MemberDetails.cshtml
@model OrderPlacement.Web.Models.Member
@{
    ViewBag.Title = "MemberDetails";
}

<h2>MemberDetails</h2>
@Html.ActionLink("Vissza", "Index");
<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.MemberId)</td>
        <td>@Html.DisplayFor(m => m.MemberId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.AddressId)</td>
        <td>@Html.DisplayFor(m => m.AddressId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Prefix)</td>
        <td>@Html.DisplayFor(m => m.Prefix)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FistName)</td>
        <td>@Html.DisplayFor(m => m.FistName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LastName)</td>
        <td>@Html.DisplayFor(m => m.LastName)</td>
    </tr>
</table>

Prog3 FF + MVC Milestone1/OrderPlacement.Web/Views/Members/MemberEdit.cshtml
@model OrderPlacement.Web.Models.Member

<h2>Hozzáadás/Felülírás</h2>

@using (Html.BeginForm("Edit", "Members"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.MemberId)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.LastName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.LastName)</div> 

    <div class="editor-label">@Html.LabelFor(m => m.FistName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.FistName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Prefix)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Prefix)</div>

    <input type="submit" value="SEND" />
}

Prog3 FF + MVC Milestone1/OrderPlacement.Web/Views/Members/MemberIndex.cshtml
@model OrderPlacement.Web.Models.MembersViewModel
@{
    ViewBag.Title = "MemberIndex";
}

<h2>A tagok kezelése</h2>
<p style="color:red; font-weight:bold">@TempData["editResult"]</p>
@Html.Partial("MemberEdit", Model.EditedMember)
@Html.Partial("MemberList", Model.ListofMembers)

Prog3 FF + MVC Milestone1/OrderPlacement.Web/Views/Members/MemberList.cshtml
@model IEnumerable<OrderPlacement.Web.Models.Member>

<h2>A tagok listája</h2>
@if (Model.Count() == 0)
{
    <p>Üres az adatbázis</p>
}
else
{
    <table border="1">
        <tr>
            <th align="center">Prefix</th>
            <th align="center">@Html.DisplayNameFor(m => m.FistName)</th>
            <th align="center">@Html.DisplayNameFor(m => m.LastName)</th>
            <th align="center">Datas</th>
            <th align="center">Remove</th>
            <th align="center">Edit</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td width="200" align="center">@Html.DisplayFor(m => item.Prefix)</td>
            <td width="200" align="center">@Html.DisplayFor(m => item.FistName)</td>
            <td width="200" align="center">@Html.DisplayFor(m => item.LastName)</td>
            <td width="200" align="center">@Html.ActionLink("[SHOW]", "Details", new { id = item.MemberId })</td>
            <td width="200" align="center">@Html.ActionLink("[DEL]", "Remove", new { id = item.MemberId })</td>
            <td width="200" align="center">@Html.ActionLink("[EDIT]", "Edit", new { id = item.MemberId })</td>
        </tr>
        }
    </table>
}